GET http://192.168.1.99:3001/api/users/648f71d0f4c85c20620cfe93

###
POST http://192.168.1.99:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "email":"example@bwg.w",
    "password":"1",
    "profile": {
        "nickname":"user2"
    }
}

###
DELETE http://192.168.1.99:3001/api/users/64a190f714cf0a76d4c864cd HTTP/1.1
Content-Type: application/json

###
PUT http://192.168.1.99:3001/api/users/64a19fac14cf0a76d4c864d4 HTTP/1.1
Content-Type: application/json

{
    "email":"example@abw.w",
    "password":"qwd",
    "profile": {
        "nickname":"user1"
    }
}

###############################################

GET http://192.168.1.99:3001/api/posts/648f71d0f4c85c20620cfe93

###
POST http://192.168.1.99:3001/api/posts HTTP/1.1
Content-Type: application/json

{
    "title": "Scream",
    "category": "weird",
    "description": "Uuuu",
    "images": [
        "image1",
        "image2",
        "image3",
        "image4",
        "image5",
        "image6"
    ],
    "comments": [
        "Well....",
        "OMG"
    ],
    "tags": [
        "tag1",
        "tag2",
        "tag3",
        "tag4",
        "tag5",
        "tag6"
    ],
    "author":"users.profile.nickname"
}

###
POST http://192.168.1.99:3001/api/posts HTTP/1.1
Content-Type: application/json

{
    "title": "dog hotdog",
    "category": "funny",
    "images": [
        "image1"
    ],
    "tags": [
        "tag1",
        "tag2"
    ]
}

###
POST http://192.168.1.99:3001/api/posts HTTP/1.1
Content-Type: application/json

{
    "title": "Dancing moomin",
    "images": [
        "image1"
    ]
}

###
DELETE http://192.168.1.99:3001/api/posts/64a2c6abd466318e87db0564 HTTP/1.1
Content-Type: application/json

###
PUT http://192.168.1.99:3001/api/posts/64a2c6fd2e688d37ada1f7ea HTTP/1.1
Content-Type: application/json

{
    "title": "habanero sauna",
    "category": "hell",
    "description": ":)",
    "images": [
        "image1",
        "image2",
        "image3"
    ],
    "comments": [
        "wow",
        "How??"
    ],
    "tags": [
        "tag1",
        "tag2"
    ],
    "author":"users.profile.nickname"
}

###
GET http://localhost:3001/fileinfo/se.png